name: 'Get Deployment ID'
description: 'Get an deployment ID for a specific REF and environment'
inputs:
  ref-to-search:
    description: 'ref of the branch/commit to search by'
    required: true
  env-name:
    description: 'environment name to get ID for'
    required: true
outputs:
  deploymentId: 
    description: 'deployment id retrieved based on ref and environment'
runs:
  using: 'node12'
  main: 'index.js'
