name: 'Seek Deployment'
description: 'Seek Deployment for a specific `ref`, `environment` and `status`'
author: james-leha@github.com, hello@cloudposse.com
branding:
  icon: 'server'
  color: 'white'
inputs:
  github-token:
    description: The GitHub token
    default: ''
  ref:
    description: 'Branch or commit SHA'
    default: ''
  environment:
    description: 'Environment name'
    default: ''
  status:
    description: 'Deployment status'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Deprecated FinalCAD/SeekDeploymentAction
      shell: bash
      run: |
        echo "::error title=Deprecated FinalCAD/SeekDeploymentAction::The action FinalCAD/SeekDeploymentAction is deprecated. Use official [cloudposse/github-action-seek-deployment](https://github.com/cloudposse/github-action-seek-deployment) instead."
        exit 1
