name: Main branch
on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  default:
    uses: cloudposse/github-actions-workflows-github-action-composite/.github/workflows/main-branch.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
    secrets:
      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"